import { v5 as uuidv5 } from "uuid";

const NAMESPACE = "6ba7b810-9dad-11d1-80b4-00c04fd430c8"; // UUID v5 namespace

export function generateStableId(title: string): string {
  return uuidv5(title, NAMESPACE);
}

// ─── Legacy seed data ────────────────────────────────────────────────────────
// These quests are superseded by the typed per-category files in src/lib/quests/.
// Kept here as a reference snapshot only — nothing imports SEED_QUESTS.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _SEED_QUESTS_UNUSED = [
  // ===== MAIN QUESTS =====
  {
    title: "Learn a New Language",
    description:
      "Dedicate yourself to learning a new spoken language. Reach conversational level through daily practice, apps, and speaking with native speakers.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Run a Half Marathon",
    description:
      "Train from couch to half marathon. Follow a structured training plan, build up mileage weekly, and cross that finish line.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-4 months",
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Build a Portfolio Website",
    description:
      "Design and develop a personal portfolio website from scratch. Include projects, blog, and contact form.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1-2 months",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Read 12 Books",
    description:
      "Read one book per month for an entire year. Mix fiction and non-fiction across genres you wouldn't normally pick.",
    type: "main",
    source: "predefined",
    difficulty: 2,
    xp_reward: 400,
    duration_label: "12 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Master a Musical Instrument",
    description:
      "Pick up an instrument and commit to daily practice. Learn to play at least 5 songs from memory.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "6-12 months",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Launch a Side Business",
    description:
      "Identify a product or service, create a business plan, build an MVP, and make your first sale.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "3-6 months",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Get Certified",
    description:
      "Earn a professional certification in your field. Study, take practice exams, and pass the official test.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-4 months",
    category: "Career",
    location: null,
    status: "available",
  },
  {
    title: "30-Day Fitness Challenge",
    description:
      "Complete a structured 30-day fitness program. Track your progress daily and push through every workout.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1 month",
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Write a Short Story Collection",
    description:
      "Write at least 5 short stories. Edit them, get feedback, and compile them into a collection.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Volunteer 100 Hours",
    description:
      "Give back to your community by volunteering 100 hours at local organizations, shelters, or events.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3-6 months",
    category: "Community",
    location: null,
    status: "available",
  },

  // ===== SIDE QUESTS =====
  {
    title: "Cook a New Recipe",
    description:
      "Find a recipe you've never tried before and make it from scratch. Bonus XP if it's from a cuisine you're unfamiliar with.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Explore a New Trail",
    description:
      "Find a hiking trail or walking path you've never been to. Spend the morning exploring nature.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "Half day",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Organize Your Desk",
    description:
      "Declutter, clean, and reorganize your workspace. A tidy desk means a tidy mind.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "Sketch Something",
    description:
      "Grab a pencil and paper (or tablet) and sketch anything — a pet, a landscape, a character. No skill required.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "30 min - 1 hour",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Visit a Local Museum",
    description:
      "Check out a museum or gallery in your area you've never been to. Take your time and actually read the plaques.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "Half day",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Fix a Bug in Open Source",
    description:
      "Find a beginner-friendly issue on GitHub, fork the repo, fix it, and submit a pull request.",
    type: "side",
    source: "predefined",
    difficulty: 3,
    xp_reward: 150,
    duration_label: "1 day",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Write a Journal Entry",
    description:
      "Sit down and write about your day, your goals, or something on your mind. Reflection is power.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "20-30 min",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Try a New Coffee Shop",
    description:
      "Find a coffee shop or café you've never visited. Bring a book or just people-watch.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Weekend Photography Walk",
    description:
      "Grab your phone or camera and go on a photo walk. Capture 20+ interesting shots and pick your best 5.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "Half day",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Build Something with LEGO",
    description:
      "Freeform build or follow a set. The goal is to create something and enjoy the process.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-3 hours",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Learn 5 Phrases in a New Language",
    description:
      "Pick a language, learn 5 useful phrases, and practice saying them out loud.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "30 min",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Do a Park Cleanup",
    description:
      "Grab a bag and spend an hour picking up litter at a local park. Small actions, big impact.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1-2 hours",
    category: "Community",
    location: null,
    status: "available",
  },
  {
    title: "Have a Board Game Night",
    description:
      "Invite friends or family for a board game session. Try a game nobody has played before.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-4 hours",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Meal Prep Sunday",
    description:
      "Prepare meals for the entire week ahead. Plan, shop, cook, and portion out your food.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "3-4 hours",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Stargaze",
    description:
      "Find a dark spot away from city lights and spend an evening looking at the stars. Use an app to identify constellations.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Outdoors",
    location: null,
    status: "available",
  },
];
