import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";
import { durationLabelToMinutes, calcQuestXP } from "@/lib/xp";

export const BUSINESS_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Write Your Business Idea",
    description: "Spend an hour writing down a business idea: the problem it solves, who it's for, and how it makes money. One page max.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Research Your Target Market",
    description: "Identify the customers for a business idea. Find 3 real competitors, read their reviews, and summarise the gap.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Send 5 Cold Outreach Messages",
    description: "Write and send 5 personalised messages to potential customers, collaborators, or mentors. Track who responds.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Set Up a Professional Profile",
    description: "Create or fully optimise a LinkedIn profile: headshot, compelling headline, 3 experience entries, and 5 skills.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Calculate a Break-Even Point",
    description: "Pick a product or service idea, estimate costs and price, then calculate how many units you need to sell to break even.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1-2 hours",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Read a Business Memoir",
    description: "Read the autobiography or business story of a founder you admire. Take notes on 3 lessons you can apply.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 weeks",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Validate an Idea with 10 People",
    description: "Ask 10 real people for feedback on a business idea. Use a short script, record their reactions, and iterate.",
    type: "side",
    source: "predefined",
    difficulty: 3,
    xp_reward: 150,
    duration_label: "1 week",
    category: "Business",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Launch a Side Business",
    description: "Identify a product or service, write a simple business plan, build a minimal version, and make your first sale.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "3-6 months",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Build an MVP in 30 Days",
    description: "Design and ship a minimum viable product for a business idea in one month. Get at least 3 real users to try it.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "1 month",
    category: "Business",
    location: null,
    status: "available",
  },
  {
    title: "Complete a Business Course",
    description: "Finish a structured business course (entrepreneurship, finance, marketing, or strategy). Pass any assessments with 80%+.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "6-8 weeks",
    category: "Business",
    location: null,
    status: "available",
  },
];

export const BUSINESS_QUESTS_WITH_IDS: Quest[] = BUSINESS_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`business-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
