import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";

const CREATIVE_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Sketch Daily Object",
    description: "Draw one everyday object in detail. Spend 20 minutes capturing its form, shadows, and texture.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "20-30 min",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Write a Poem",
    description: "Compose a poem about your day, a memory, or an emotion. Don't worry about perfection—just express.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "30 min",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Learn a Song on Guitar",
    description: "Pick a simple song and learn to play it on guitar or ukulele. Practice chords and strumming.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Photo Walk",
    description: "Take 20 photos during a walk. Look for interesting compositions, colors, and moments.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Try Watercolor",
    description: "Paint a simple landscape or abstract piece with watercolors. Experiment with wet-on-wet techniques.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1-2 hours",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Create Digital Art",
    description: "Use Procreate, Photoshop, or free alternatives like Krita to create a digital illustration.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Make a Short Video",
    description: "Film and edit a 1-minute video about your day or a hobby. Use your phone and free editing apps.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Creative",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "30-Day Drawing Challenge",
    description: "Draw something every day for 30 days using prompts. Share your progress and watch your skills grow.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Write 5 Short Stories",
    description: "Write five short stories (1000+ words each). Edit them and share with friends for feedback.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2 months",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Learn an Instrument",
    description: "Choose piano, guitar, or another instrument. Practice 30 min daily for 2 months. Learn 5 songs.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Complete a Photography Series",
    description: "Create a 20-photo series on a theme. Edit consistently and create a portfolio or photo book.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1-2 months",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Build a Craft Project",
    description: "Choose woodworking, knitting, pottery, or another craft. Complete a substantial project from start to finish.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1-2 months",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Create a YouTube Channel",
    description: "Start a YouTube channel on any topic. Create 10 videos, learn editing, and grow to 100 subscribers.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Write a Novel",
    description: "Write a 50,000+ word novel. Outline, draft, and do one round of revisions. Participate in NaNoWriMo or solo.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "3-6 months",
    category: "Creative",
    location: null,
    status: "available",
  },
  {
    title: "Master Digital Illustration",
    description: "Learn digital art fundamentals: anatomy, color theory, composition. Create a 10-piece portfolio.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-4 months",
    category: "Creative",
    location: null,
    status: "available",
  },
];

export const CREATIVE_QUESTS_WITH_IDS: Quest[] = CREATIVE_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`creative-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
