import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";

export const CULTURE_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Visit a Museum or Gallery",
    description: "Spend a few hours at a museum, art gallery, or historical site you've never been to. Read the descriptions and reflect.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "Half day",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Watch a Foreign Language Film",
    description: "Watch a critically acclaimed film in a language you don't speak. No English dubbing — subtitles only. Reflect on what you noticed.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-3 hours",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Attend a Live Performance",
    description: "Go to a live concert, theatre show, stand-up set, dance performance, or spoken word event. Experience art in real time.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-4 hours",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Try a Traditional Dish",
    description: "Cook or eat a dish from a culture other than your own that you've never tried. Learn a little about its origin.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-3 hours",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Learn 20 Phrases in a New Language",
    description: "Pick a language and learn 20 useful everyday phrases. Practise pronunciation and use them in a real or simulated conversation.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1 week",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Read a Classic Novel",
    description: "Read a classic novel from the 20th century or earlier. Write a short reflection on what surprised you most.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 weeks",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Attend a Cultural Festival",
    description: "Go to a cultural festival, street fair, or community celebration that highlights a culture you're curious about.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "Half day",
    category: "Culture",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Reach Conversational Level in a Language",
    description: "Commit to learning a new language to conversational level. Use daily practice, apps, classes, and speaking with native speakers. Pass a self-assessment test at the end.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Deep Dive into a Historical Period",
    description: "Study one historical period or civilisation in depth. Read 3 books, watch 2 documentaries, and write a 1-page summary of your key insights.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2-3 months",
    category: "Culture",
    location: null,
    status: "available",
  },
  {
    title: "Read 5 Classic Novels",
    description: "Read five classic works of literature from different eras or cultures. Journal your thoughts after each one.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3-5 months",
    category: "Culture",
    location: null,
    status: "available",
  },
];

export const CULTURE_QUESTS_WITH_IDS: Quest[] = CULTURE_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`culture-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
