import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";

const EDUCATION_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Learn 10 Phrases in a New Language",
    description: "Pick any language and learn 10 useful phrases. Practice pronunciation with an app or video.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Read a Short Book",
    description: "Read a book under 200 pages in one sitting or over a weekend. Fiction or non-fiction.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "4-6 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Watch a Documentary",
    description: "Watch an educational documentary on history, science, or nature. Take notes on key facts.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Complete an Online Course Module",
    description: "Finish one full module from a free online course on Coursera, edX, or Khan Academy.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Visit a Museum",
    description: "Spend at least 2 hours at a museum. Read the plaques and learn about 5 exhibits in detail.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "Half day",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Research a Topic",
    description: "Pick a topic you're curious about. Research it for 3+ hours and write a summary.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "3-4 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Attend a Lecture or Talk",
    description: "Go to a local lecture, TED talk viewing, or university open lecture. Take notes.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-3 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Read 12 Books in a Year",
    description: "Read one book per month. Mix genres: fiction, non-fiction, biography, science.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "12 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Learn a New Language",
    description: "Study a language to conversational level. Use apps, tutors, and practice 30 min daily for 6 months.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "6 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Complete a College Course",
    description: "Take and pass a full college-level course online. Includes lectures, assignments, and exams.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-4 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Learn to Speed Read",
    description: "Practice speed reading techniques. Double your reading speed while maintaining comprehension.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1-2 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Master a Historical Era",
    description: "Deep dive into one historical period. Read 5+ books, watch documentaries, visit sites if possible.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2-3 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Get a Professional Certification",
    description: "Earn a certification relevant to your field: PMP, CFA, CPA, or industry-specific credentials.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Learn a Scientific Subject",
    description: "Study physics, chemistry, biology, or astronomy at college level. Complete problem sets and labs.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-4 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Become a Subject Expert",
    description: "Choose a niche topic. Read 20+ books/papers, follow experts, and give a presentation on it.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "6-12 months",
    category: "Education",
    location: null,
    status: "available",
  },
];

export const EDUCATION_QUESTS_WITH_IDS: Quest[] = EDUCATION_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`education-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
