import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/stable-id";

const EDUCATION_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Learn 10 Phrases in a New Language",
    description: "Pick any language and learn 10 useful phrases. Practice pronunciation with an app or video.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Read a Short Book",
    description: "Read a book under 200 pages in one sitting or over a weekend. Fiction or non-fiction.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "4-6 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Watch a Documentary",
    description: "Watch an educational documentary on history, science, or nature. Take notes on key facts.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Complete an Online Course Module",
    description: "Finish one full module from a free online course on Coursera, edX, or Khan Academy.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Visit a Museum",
    description: "Spend at least 2 hours at a museum. Read the plaques and learn about 5 exhibits in detail.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "Half day",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Research a Topic",
    description: "Pick a topic you're curious about. Research it for 3+ hours and write a summary.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "3-4 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Attend a Lecture or Talk",
    description: "Go to a local lecture, TED talk viewing, or university open lecture. Take notes.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-3 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Read 12 Books in a Year",
    description: "Read one book per month. Mix genres: fiction, non-fiction, biography, science.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "12 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Learn a New Language",
    description: "Study a language to conversational level. Use apps, tutors, and practice 30 min daily for 6 months.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "6 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Complete a College Course",
    description: "Take and pass a full college-level course online. Includes lectures, assignments, and exams.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-4 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Learn to Speed Read",
    description: "Practice speed reading techniques. Double your reading speed while maintaining comprehension.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1-2 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Master a Historical Era",
    description: "Deep dive into one historical period. Read 5+ books, watch documentaries, visit sites if possible.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2-3 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Get a Professional Certification",
    description: "Earn a certification relevant to your field: PMP, CFA, CPA, or industry-specific credentials.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Learn a Scientific Subject",
    description: "Study physics, chemistry, biology, or astronomy at college level. Complete problem sets and labs.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-4 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Become a Subject Expert",
    description: "Choose a niche topic. Read 20+ books/papers, follow experts, and give a presentation on it.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "6-12 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Learn CPR or First Aid",
    description: "Take a certified CPR and first aid class in person. A skill worth having — and one you'll hopefully never need.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Binge a Podcast Series",
    description: "Pick a documentary or narrative podcast series and listen to the whole series. Write down the most surprising thing you learned.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 75,
    duration_label: "2-3 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Read a Philosophy Essay",
    description: "Choose a classic essay — Montaigne, Camus, Russell, or de Beauvoir. Read carefully and write a one-page response in your own words.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "30-45 min",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Study Chess Openings",
    description: "Learn 5 fundamental chess openings and the ideas behind each one. Play 10 games applying what you studied.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1-2 hours",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Teach Someone Something",
    description: "Pick a skill or topic you know well and spend 20+ minutes teaching it to someone else. Explaining deepens understanding more than any textbook.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 75,
    duration_label: "30-45 min",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Nonfiction Topic Challenge",
    description: "Read one book from each of 5 different nonfiction genres — e.g., history, business, philosophy, science, and memoir. Each book should come from a genre you don't normally read.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3-4 months",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Study a New Field for 30 Days",
    description: "Pick a subject outside your expertise — economics, psychology, astronomy, or philosophy. Spend 30 minutes each day reading or listening for 30 consecutive days. Write a summary at the end.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Education",
    location: null,
    status: "available",
  },
  {
    title: "Reach 1000+ Chess Rating",
    description: "Improve your chess to 1000+ on Lichess or Chess.com. Study tactics, endgames, and openings. Play and analyse games regularly over 3 months.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3 months",
    category: "Education",
    location: null,
    status: "available",
  },
];

export const EDUCATION_QUESTS_WITH_IDS: Quest[] = EDUCATION_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`education-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
