import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/stable-id";
import { durationLabelToMinutes, calcQuestXP } from "@/lib/xp";

const FITNESS_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Morning Stretch Routine",
    description: "Start your day with a 10-minute full-body stretch. Focus on neck, shoulders, back, and legs to wake up your muscles.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    duration_label: "10-15 min",
    duration_minutes: durationLabelToMinutes("10-15 min"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("10-15 min"), 1),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "7-Day Step Challenge",
    description: "Walk 8,000 steps every day for a week. Use a fitness tracker or phone app to count.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    duration_label: "7 days",
    duration_minutes: durationLabelToMinutes("7 days"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("7 days"), 2),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Plank Challenge",
    description: "Hold a plank position for as long as you can. Start with 30 seconds and build up over 5 days.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    duration_label: "5 days",
    duration_minutes: durationLabelToMinutes("5 days"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("5 days"), 2),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Yoga Flow Session",
    description: "Complete a 30-minute yoga flow video. Focus on breathing and smooth transitions between poses.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    duration_label: "30-45 min",
    duration_minutes: durationLabelToMinutes("30-45 min"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("30-45 min"), 2),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "HIIT Workout",
    description: "Do a high-intensity interval training session: 30 seconds work, 30 seconds rest, for 20 minutes.",
    type: "side",
    source: "predefined",
    difficulty: 3,
    duration_label: "20-30 min",
    duration_minutes: durationLabelToMinutes("20-30 min"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("20-30 min"), 3),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Swim 20 Laps",
    description: "Swim 20 laps at your local pool. Take breaks as needed and focus on form.",
    type: "side",
    source: "predefined",
    difficulty: 3,
    duration_label: "45-60 min",
    duration_minutes: durationLabelToMinutes("45-60 min"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("45-60 min"), 3),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Bike 20 Miles",
    description: "Go for a 20-mile bike ride. Choose a scenic route and enjoy the journey.",
    type: "side",
    source: "predefined",
    difficulty: 3,
    duration_label: "2-3 hours",
    duration_minutes: durationLabelToMinutes("2-3 hours"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("2-3 hours"), 3),
    category: "Fitness",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "30-Day Fitness Habit",
    description: "Exercise for at least 20 minutes every day for 30 days. Mix cardio, strength, and flexibility.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Couch to 5K",
    description: "Follow a structured program to run a 5K. Start with walk-run intervals and build endurance over 8 weeks.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    duration_label: "8 weeks",
    duration_minutes: durationLabelToMinutes("8 weeks"),
    xp_reward: calcQuestXP("main", durationLabelToMinutes("8 weeks"), 3),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Strength Training Mastery",
    description: "Learn proper form for squats, deadlifts, bench press, and overhead press. Train 3x/week for 2 months.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    duration_label: "2 months",
    duration_minutes: durationLabelToMinutes("2 months"),
    xp_reward: calcQuestXP("main", durationLabelToMinutes("2 months"), 4),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Complete a Half Marathon",
    description: "Train systematically for 12 weeks and complete a 13.1 mile race. Follow a training plan with rest days.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3 months",
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "30-Day Yoga Journey",
    description: "Practice yoga daily for 30 days. Progress from beginner to intermediate poses. Document your flexibility gains.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Learn a Martial Art",
    description: "Take classes in karate, judo, bjj, or boxing twice a week for 3 months. Learn forms and sparring basics.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3 months",
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Master a Sport",
    description: "Choose tennis, basketball, soccer, or rock climbing. Practice 2-3x/week for 3 months and join a local league.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    duration_label: "3-6 months",
    duration_minutes: durationLabelToMinutes("3-6 months"),
    xp_reward: calcQuestXP("main", durationLabelToMinutes("3-6 months"), 4),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Complete a Triathlon",
    description: "Train for and complete a sprint triathlon. Balance swimming, cycling, and running training over 4 months.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    duration_label: "4-6 months",
    duration_minutes: durationLabelToMinutes("4-6 months"),
    xp_reward: calcQuestXP("main", durationLabelToMinutes("4-6 months"), 5),
    category: "Fitness",
    location: null,
    status: "available",
  },
  // ── New Side Quests ──────────────────────────────────────────────────────
  {
    title: "Jump Rope Blitz",
    description: "Grab a jump rope and aim for 100 consecutive jumps without stopping. Take breaks and retry until you hit it.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    duration_label: "10-15 min",
    duration_minutes: durationLabelToMinutes("10-15 min"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("10-15 min"), 1),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Dance Cardio Session",
    description: "Follow a 30-minute dance cardio video on YouTube. No partner or experience needed — just move and have fun.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    duration_label: "30-45 min",
    duration_minutes: durationLabelToMinutes("30-45 min"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("30-45 min"), 2),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Bodyweight Circuit",
    description: "Complete 3 rounds: 20 squats, 15 push-ups, 10 lunges each leg, 30-second wall sit. Rest 90 seconds between rounds.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    duration_label: "20-30 min",
    duration_minutes: durationLabelToMinutes("20-30 min"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("20-30 min"), 2),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Sunset Run",
    description: "Lace up and run 3 miles at whatever pace feels good — no GPS stress, no PB chasing. Just you and the evening air.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    duration_label: "30-45 min",
    duration_minutes: durationLabelToMinutes("30-45 min"),
    xp_reward: calcQuestXP("side", durationLabelToMinutes("30-45 min"), 2),
    category: "Fitness",
    location: null,
    status: "available",
  },
  // ── New Main Quests ──────────────────────────────────────────────────────
  {
    title: "Learn to Handstand",
    description: "Practice 10–15 minutes of handstand drills daily for 2 months: wall holds, kick-ups, shoulder conditioning. Goal: 5-second freestanding handstand.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    duration_label: "2 months",
    duration_minutes: durationLabelToMinutes("2 months"),
    xp_reward: calcQuestXP("main", durationLabelToMinutes("2 months"), 4),
    category: "Fitness",
    location: null,
    status: "available",
  },
  {
    title: "Mobility & Flexibility Overhaul",
    description: "Stretch and mobilise daily for 2 months. Target hips, hamstrings, spine, and shoulders. Document progress photos each week.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    duration_label: "2 months",
    duration_minutes: durationLabelToMinutes("2 months"),
    xp_reward: calcQuestXP("main", durationLabelToMinutes("2 months"), 3),
    category: "Fitness",
    location: null,
    status: "available",
  },
];

export const FITNESS_QUESTS_WITH_IDS: Quest[] = FITNESS_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`fitness-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
