import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";

const FOOD_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Cook a New Recipe",
    description: "Try a recipe you've never made before. Bonus if it's from a cuisine you're unfamiliar with.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Bake Something from Scratch",
    description: "Bake bread, cookies, or cake from scratch—no mixes. Enjoy the smell of fresh baking.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Try a New Restaurant",
    description: "Visit a restaurant you've never been to. Order something adventurous from the menu.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Meal Prep Sunday",
    description: "Prepare a week's worth of lunches or dinners. Portion them out for easy grab-and-go.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "3-4 hours",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Make Homemade Pasta",
    description: "Create pasta from scratch. Mix dough, roll it out, and cook with your favorite sauce.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Food",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Cook 30 New Recipes",
    description: "Make 30 different recipes over 3 months. Document with photos and notes on what you learned.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3 months",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Master a Cuisine",
    description: "Deep dive into one cuisine: Italian, Thai, Mexican, etc. Learn 10+ dishes and their techniques.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2-3 months",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "30-Day No Restaurant Challenge",
    description: "Cook every meal at home for 30 days. Plan groceries, prep ingredients, and save money.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Start a Garden",
    description: "Grow vegetables or herbs. Plant seeds, tend them for 3 months, and cook with your harvest.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3-6 months",
    category: "Food",
    location: null,
    status: "available",
  },
  {
    title: "Fermentation Project",
    description: "Make sourdough starter, kimchi, kombucha, or kraut. Maintain it for 30+ days.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1-2 months",
    category: "Food",
    location: null,
    status: "available",
  },
];

export const FOOD_QUESTS_WITH_IDS: Quest[] = FOOD_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`food-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
