import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";

const LIFESTYLE_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Declutter a Room",
    description: "Choose one room and remove 20+ items you don't need. Donate or discard responsibly.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-4 hours",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  {
    title: "Organize Your Digital Files",
    description: "Clean up your computer: organize folders, delete duplicates, and clear your desktop.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-3 hours",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  {
    title: "Create a Budget",
    description: "Track your spending for a month and create a realistic budget with savings goals.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "3-4 hours",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  {
    title: "No-Spend Weekend",
    description: "Spend no money for 48 hours. Find free activities and use what you already have.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2 days",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  {
    title: "Deep Clean Your Space",
    description: "Thoroughly clean your home: scrub, vacuum, dust, and organize every corner.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "4-6 hours",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "30-Day Minimalism Challenge",
    description: "Remove one item on day 1, two on day 2, etc. Declutter 465+ items total.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  {
    title: "Build an Emergency Fund",
    description: "Save 3 months of expenses. Set up automatic transfers and track progress monthly.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "6-12 months",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  {
    title: "Organize Entire Home",
    description: "Systematically organize every room. Create storage systems and maintain them for 3 months.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1-2 months",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  {
    title: "Wake Up Early for 30 Days",
    description: "Wake up at 6 AM (or 1 hour earlier than usual) for 30 days. Build a morning routine.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
  {
    title: "Year of No Shopping",
    description: "Buy nothing non-essential for a year. Only replace worn-out necessities.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "12 months",
    category: "Lifestyle",
    location: null,
    status: "available",
  },
];

export const LIFESTYLE_QUESTS_WITH_IDS: Quest[] = LIFESTYLE_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`lifestyle-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
