import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";

const OUTDOORS_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Explore a New Trail",
    description: "Find a hiking or walking trail you've never been to. Spend at least an hour exploring.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-3 hours",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Sunrise Watch",
    description: "Wake up early and watch the sunrise from a scenic outdoor location. Bring coffee.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2 hours",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Stargazing Night",
    description: "Find a dark spot away from city lights and identify 5 constellations using an app.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-3 hours",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Geocaching Adventure",
    description: "Try geocaching. Find at least 3 caches using GPS coordinates. It's like a real-world treasure hunt!",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "Half day",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Kayaking or Canoeing",
    description: "Rent a kayak or canoe and spend 2+ hours on the water. Explore a lake or gentle river.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "3-4 hours",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Camp for a Weekend",
    description: "Spend two nights camping. Set up a tent, cook over a fire, and disconnect from technology.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2-3 days",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Summit a Mountain",
    description: "Hike to the summit of a significant peak. Plan the route, pack properly, and enjoy the view.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1-2 days",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Multi-Day Backpacking",
    description: "Complete a 3+ day backpacking trip. Carry everything you need and camp in the wilderness.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-5 days",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Learn Rock Climbing",
    description: "Take a course and climb both indoors and outdoors. Learn belaying, knots, and safety.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Outdoors",
    location: null,
    status: "available",
  },
  {
    title: "Plan a Road Trip",
    description: "Plan and execute a 500+ mile road trip with multiple stops. Document the journey.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1 week",
    category: "Outdoors",
    location: null,
    status: "available",
  },
];

export const OUTDOORS_QUESTS_WITH_IDS: Quest[] = OUTDOORS_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`outdoors-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
