import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";
import { durationLabelToMinutes, calcQuestXP } from "@/lib/xp";

export const PRODUCTIVITY_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Organise Your Workspace",
    description: "Declutter, clean, and reorganise your desk or home office. Remove everything that doesn't belong and set up a system to keep it tidy.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "Do a Weekly Review",
    description: "Block 30 minutes to review the past week: what you completed, what stalled, and what's next. Write it down and commit to 3 priorities for the coming week.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "30-45 min",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "Reach Inbox Zero",
    description: "Process your email inbox until it's completely empty. Archive, reply, delete, or delegate every message.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1-3 hours",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "Set Up a Task Management System",
    description: "Choose a task manager (Notion, Todoist, Things, pen & paper) and set it up with your active projects and recurring tasks. Use it every day for one week.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1 week",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "Time-Block Your Day",
    description: "Schedule every hour of one working day in advance. Block time for focused work, meetings, breaks, and admin. Reflect at the end on how it went.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1 day",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "Do a Digital Declutter",
    description: "Delete unused apps, clear your desktop, organise your downloads folder, and unsubscribe from 10+ email lists.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "Build a Morning Routine",
    description: "Design and stick to a morning routine for 7 consecutive days. Include at least: movement, intention-setting, and a no-phone window.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "7 days",
    category: "Productivity",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Master a Productivity Method",
    description: "Pick a proven productivity system (GTD, Zettelkasten, Time Blocking, Deep Work) and implement it fully for 30 days. Document what changes.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "1 month",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "30-Day No Social Media Challenge",
    description: "Go 30 days without passive social media scrolling. Replace that time deliberately: reading, learning, creating. Track how you feel each week.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "1 month",
    category: "Productivity",
    location: null,
    status: "available",
  },
  {
    title: "Complete a 12-Week Deep Work Sprint",
    description: "Identify your most important project. Dedicate 3+ hours of focused deep work to it every weekday for 12 weeks. Produce a tangible deliverable at the end.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "3 months",
    category: "Productivity",
    location: null,
    status: "available",
  },
];

export const PRODUCTIVITY_QUESTS_WITH_IDS: Quest[] = PRODUCTIVITY_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`productivity-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
