import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/stable-id";
import { defineQuest } from "@/lib/quests/factory";

const SOCIAL_QUESTS = [
  // Side Quests
  defineQuest({
    title: "Attend a Meetup",
    description: "Go to a local meetup about a topic you're interested in. Talk to at least 3 new people.",
    type: "side",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Social",
  }),
  defineQuest({
    title: "Host a Dinner Party",
    description: "Invite 4+ friends over for a home-cooked meal. Plan the menu and create a welcoming atmosphere.",
    type: "side",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "4-6 hours",
    category: "Social",
  }),
  defineQuest({
    title: "Volunteer for a Day",
    description: "Spend 4+ hours volunteering at a local charity, shelter, or community event.",
    type: "side",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "Half day",
    category: "Social",
  }),
  defineQuest({
    title: "Reconnect with an Old Friend",
    description: "Reach out to someone you haven't spoken to in 6+ months. Have a meaningful conversation.",
    type: "side",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Social",
  }),
  defineQuest({
    title: "Join a Club",
    description: "Sign up for a local club: book club, hiking group, board game night, or sports league.",
    type: "side",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-3 hours",
    category: "Social",
  }),
  // Main Quests
  defineQuest({
    title: "Volunteer 50 Hours",
    description: "Give back to your community through 50 hours of volunteer work across various organizations.",
    type: "main",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3-6 months",
    category: "Social",
  }),
  defineQuest({
    title: "Organize a Community Event",
    description: "Plan and execute a local event: cleanup, fundraiser, or social gathering. Get 20+ people to attend.",
    type: "main",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Social",
  }),
  defineQuest({
    title: "Build a Professional Network",
    description: "Attend 10 networking events. Connect with 50 professionals on LinkedIn. Have 5 coffee chats.",
    type: "main",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3 months",
    category: "Social",
  }),
  defineQuest({
    title: "Mentor Someone",
    description: "Guide someone junior in your field. Meet bi-weekly for 3 months. Help them achieve a specific goal.",
    type: "main",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3 months",
    category: "Social",
  }),
  defineQuest({
    title: "Join a Board or Committee",
    description: "Become a member of a non-profit board or community committee. Attend meetings for 6 months.",
    type: "main",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "6 months",
    category: "Social",
  }),
  defineQuest({
    title: "Write 5 Appreciation Letters",
    description: "Handwrite (or type) a heartfelt thank-you note to 5 people who've positively shaped your life. Send them all.",
    type: "side",
    difficulty: 1,
    xp_reward: 75,
    duration_label: "1-2 hours",
    category: "Social",
  }),
  defineQuest({
    title: "Host a Games Night",
    description: "Invite 4+ friends over for a board game, card game, or quiz night. You host, you pick the games, you supply the snacks.",
    type: "side",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "3-4 hours",
    category: "Social",
  }),
  defineQuest({
    title: "Strike Up 5 Conversations with Strangers",
    description: "In one day, genuinely chat with 5 people you don't know — a café barista, someone in a queue, a neighbour. Real conversation, not small talk.",
    type: "side",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1 day",
    category: "Social",
  }),
  defineQuest({
    title: "Take an Improv Comedy Course",
    description: "Enrol in a beginner improv course and attend all sessions over 6–8 weeks. Perform in the end-of-course show.",
    type: "main",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2 months",
    category: "Social",
  }),
  defineQuest({
    title: "Join Toastmasters for a Term",
    description: "Attend a Toastmasters club weekly for 3 months. Deliver at least 5 prepared speeches and take on a meeting role each session.",
    type: "main",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3 months",
    category: "Social",
  }),
  defineQuest({
    title: "Find a Pen Pal",
    description: "Connect with someone in another country through a pen pal platform and exchange at least 12 letters or emails over 6 months. Build a real cross-cultural friendship.",
    type: "main",
    difficulty: 2,
    xp_reward: 600,
    duration_label: "6 months",
    category: "Social",
  }),
];

export const SOCIAL_QUESTS_WITH_IDS: Quest[] = SOCIAL_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`social-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
