import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";
import { durationLabelToMinutes, calcQuestXP } from "@/lib/xp";

const SOCIAL_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Attend a Meetup",
    description: "Go to a local meetup about a topic you're interested in. Talk to at least 3 new people.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Host a Dinner Party",
    description: "Invite 4+ friends over for a home-cooked meal. Plan the menu and create a welcoming atmosphere.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "4-6 hours",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Volunteer for a Day",
    description: "Spend 4+ hours volunteering at a local charity, shelter, or community event.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "Half day",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Reconnect with an Old Friend",
    description: "Reach out to someone you haven't spoken to in 6+ months. Have a meaningful conversation.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1-2 hours",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Join a Club",
    description: "Sign up for a local club: book club, hiking group, board game night, or sports league.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "2-3 hours",
    category: "Social",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Volunteer 50 Hours",
    description: "Give back to your community through 50 hours of volunteer work across various organizations.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3-6 months",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Organize a Community Event",
    description: "Plan and execute a local event: cleanup, fundraiser, or social gathering. Get 20+ people to attend.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Build a Professional Network",
    description: "Attend 10 networking events. Connect with 50 professionals on LinkedIn. Have 5 coffee chats.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3 months",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Mentor Someone",
    description: "Guide someone junior in your field. Meet bi-weekly for 3 months. Help them achieve a specific goal.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3 months",
    category: "Social",
    location: null,
    status: "available",
  },
  {
    title: "Join a Board or Committee",
    description: "Become a member of a non-profit board or community committee. Attend meetings for 6 months.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "6 months",
    category: "Social",
    location: null,
    status: "available",
  },
];

export const SOCIAL_QUESTS_WITH_IDS: Quest[] = SOCIAL_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`social-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
