import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/stable-id";
import { defineQuest } from "@/lib/quests/factory";

const TECH_QUESTS = [
  // Side Quests
  defineQuest({
    title: "Fix a Bug in Open Source",
    description: "Find a beginner-friendly issue on GitHub, fork the repo, fix it, and submit a pull request.",
    difficulty: 3,
    xp_reward: 150,
    duration_label: "2-4 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Build a Calculator App",
    description: "Create a calculator with HTML, CSS, and JavaScript. Support basic operations and a clean UI.",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Learn Git Basics",
    description: "Master init, add, commit, push, pull, branch, and merge. Create a repo and practice the workflow.",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Create a Personal API",
    description: "Build a simple REST API with Node.js or Python. Include GET, POST, PUT, DELETE endpoints.",
    difficulty: 3,
    xp_reward: 150,
    duration_label: "3-5 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Automate a Task",
    description: "Write a script to automate a repetitive task. Could be file organization, data processing, or notifications.",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Deploy a Website",
    description: "Build a simple site and deploy it to Vercel, Netlify, or GitHub Pages. Set up CI/CD if possible.",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Create a Discord Bot",
    description: "Build a bot that responds to commands, sends messages, or moderates. Host it on a free tier.",
    difficulty: 3,
    xp_reward: 150,
    duration_label: "4-6 hours",
    category: "Tech",
  }),
  // Main Quests
  defineQuest({
    title: "Build a Portfolio Website",
    description: "Design and develop a personal portfolio with projects, blog, and contact. Use React or Next.js.",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2-4 weeks",
    category: "Tech",
  }),
  defineQuest({
    title: "Complete a Coding Bootcamp",
    description: "Finish freeCodeCamp's JavaScript curriculum, or The Odin Project. Build all required projects.",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Tech",
  }),
  defineQuest({
    title: "Create a Mobile App",
    description: "Build and publish a mobile app using React Native or Flutter. Include 3+ features and get 10 downloads.",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Tech",
  }),
  defineQuest({
    title: "Learn Machine Learning Basics",
    description: "Complete an ML course. Build a project using scikit-learn or TensorFlow. Train and evaluate a model.",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Tech",
  }),
  defineQuest({
    title: "Build a SaaS Product",
    description: "Create a web app with auth, database, and payments. Launch it and get 5 paying or 100 free users.",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "3-6 months",
    category: "Tech",
  }),
  defineQuest({
    title: "Get AWS Certified",
    description: "Study for and pass the AWS Certified Cloud Practitioner or Developer Associate exam.",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Tech",
  }),
  defineQuest({
    title: "Contribute to Major Open Source",
    description: "Make 5 meaningful contributions to a major open-source project. Includes docs, tests, or features.",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Tech",
  }),
  defineQuest({
    title: "Build a Game",
    description: "Create a complete game with Unity, Godot, or web technologies. Include menus, gameplay, and sound.",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "3-6 months",
    category: "Tech",
  }),
  defineQuest({
    title: "Master the Command Line",
    description: "Learn 20 essential terminal commands: navigation, file manipulation, piping, grep, and permissions. Complete a beginner CLI course.",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1-2 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Set Up a Raspberry Pi",
    description: "Flash an OS, SSH in, and complete a beginner project: weather display, retro gaming console, or home media server.",
    difficulty: 3,
    xp_reward: 250,
    duration_label: "2-4 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Build a Browser Extension",
    description: "Create a simple Chrome or Firefox extension that does one useful thing: tab manager, focus timer, or custom new-tab page.",
    difficulty: 3,
    xp_reward: 250,
    duration_label: "2-4 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Scrape and Visualise Data",
    description: "Use Python or JavaScript to scrape a public dataset, clean it, and produce one compelling chart. Post it somewhere.",
    difficulty: 3,
    xp_reward: 200,
    duration_label: "2-3 hours",
    category: "Tech",
  }),
  defineQuest({
    title: "Cybersecurity Fundamentals",
    description: "Complete a cybersecurity course (TryHackMe, Hack The Box, or similar). Finish 3 beginner CTF challenges and write a summary of what you learned.",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2 months",
    category: "Tech",
  }),
  defineQuest({
    title: "Learn 3D Modelling",
    description: "Work through a Blender beginner course over 2 months. Create and render at least 5 original models — one of which is animated.",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2 months",
    category: "Tech",
  }),
];

export const TECH_QUESTS_WITH_IDS: Quest[] = TECH_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`tech-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
