import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";
import { durationLabelToMinutes, calcQuestXP } from "@/lib/xp";

const TECH_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "Fix a Bug in Open Source",
    description: "Find a beginner-friendly issue on GitHub, fork the repo, fix it, and submit a pull request.",
    type: "side",
    source: "predefined",
    difficulty: 3,
    xp_reward: 150,
    duration_label: "2-4 hours",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Build a Calculator App",
    description: "Create a calculator with HTML, CSS, and JavaScript. Support basic operations and a clean UI.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Learn Git Basics",
    description: "Master init, add, commit, push, pull, branch, and merge. Create a repo and practice the workflow.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Create a Personal API",
    description: "Build a simple REST API with Node.js or Python. Include GET, POST, PUT, DELETE endpoints.",
    type: "side",
    source: "predefined",
    difficulty: 3,
    xp_reward: 150,
    duration_label: "3-5 hours",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Automate a Task",
    description: "Write a script to automate a repetitive task. Could be file organization, data processing, or notifications.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-4 hours",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Deploy a Website",
    description: "Build a simple site and deploy it to Vercel, Netlify, or GitHub Pages. Set up CI/CD if possible.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "2-3 hours",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Create a Discord Bot",
    description: "Build a bot that responds to commands, sends messages, or moderates. Host it on a free tier.",
    type: "side",
    source: "predefined",
    difficulty: 3,
    xp_reward: 150,
    duration_label: "4-6 hours",
    category: "Tech",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "Build a Portfolio Website",
    description: "Design and develop a personal portfolio with projects, blog, and contact. Use React or Next.js.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2-4 weeks",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Complete a Coding Bootcamp",
    description: "Finish freeCodeCamp's JavaScript curriculum, or The Odin Project. Build all required projects.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Create a Mobile App",
    description: "Build and publish a mobile app using React Native or Flutter. Include 3+ features and get 10 downloads.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Learn Machine Learning Basics",
    description: "Complete an ML course. Build a project using scikit-learn or TensorFlow. Train and evaluate a model.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Build a SaaS Product",
    description: "Create a web app with auth, database, and payments. Launch it and get 5 paying or 100 free users.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "3-6 months",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Get AWS Certified",
    description: "Study for and pass the AWS Certified Cloud Practitioner or Developer Associate exam.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "2-3 months",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Contribute to Major Open Source",
    description: "Make 5 meaningful contributions to a major open-source project. Includes docs, tests, or features.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "3-6 months",
    category: "Tech",
    location: null,
    status: "available",
  },
  {
    title: "Build a Game",
    description: "Create a complete game with Unity, Godot, or web technologies. Include menus, gameplay, and sound.",
    type: "main",
    source: "predefined",
    difficulty: 5,
    xp_reward: 1000,
    duration_label: "3-6 months",
    category: "Tech",
    location: null,
    status: "available",
  },
];

export const TECH_QUESTS_WITH_IDS: Quest[] = TECH_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`tech-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
