import { Quest } from "@/lib/types";
import { generateStableId } from "@/lib/seed-quests";

export const WELLNESS_QUESTS: Omit<Quest, "id" | "created_at" | "user_id">[] = [
  // Side Quests
  {
    title: "10-Minute Meditation",
    description: "Sit quietly and meditate for 10 minutes. Focus on your breath. Use an app if you're new.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "10-15 min",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Digital Detox Day",
    description: "Go 24 hours without social media. Notice how you feel and what you do with your time instead.",
    type: "side",
    source: "predefined",
    difficulty: 2,
    xp_reward: 100,
    duration_label: "1 day",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Journal Your Thoughts",
    description: "Write three pages of stream-of-consciousness journaling. Don't edit—just let thoughts flow.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "30 min",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Gratitude List",
    description: "Write down 10 things you're grateful for. Be specific and reflect on why each matters.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "15-20 min",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Perfect Sleep Night",
    description: "Create a sleep ritual: no screens 1 hour before bed, cool room, and 8 hours of sleep.",
    type: "side",
    source: "predefined",
    difficulty: 1,
    xp_reward: 50,
    duration_label: "1 night",
    category: "Wellness",
    location: null,
    status: "available",
  },
  // Main Quests
  {
    title: "30-Day Meditation Challenge",
    description: "Meditate for at least 10 minutes every day for 30 days. Track your mood and focus improvements.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Establish Morning Routine",
    description: "Create and stick to a morning routine for 30 days. Include movement, mindfulness, and planning.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "30 days",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Therapy Journey",
    description: "Attend 10+ therapy sessions. Work on specific goals with a licensed therapist.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "3 months",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Fix Your Sleep Schedule",
    description: "Maintain consistent sleep/wake times for 60 days. Aim for 7-8 hours. Track energy levels.",
    type: "main",
    source: "predefined",
    difficulty: 3,
    xp_reward: 600,
    duration_label: "2 months",
    category: "Wellness",
    location: null,
    status: "available",
  },
  {
    title: "Year of Mindfulness",
    description: "Practice mindfulness daily for a year. Mix meditation, mindful eating, walking, and breathing.",
    type: "main",
    source: "predefined",
    difficulty: 4,
    xp_reward: 800,
    duration_label: "12 months",
    category: "Wellness",
    location: null,
    status: "available",
  },
];

export const WELLNESS_QUESTS_WITH_IDS: Quest[] = WELLNESS_QUESTS.map((q) => ({
  ...q,
  id: generateStableId(`wellness-${q.title}`),
  user_id: null,
  created_at: new Date().toISOString(),
}));
